[project]
name = "recall-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "warrockhali", email = "warrockhali@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1,<2",
    "fastapi[standard]>=0.141.1",
    "psycopg[binary]>=3,<4",
    "python-dotenv>=1,<2",
    "sqlalchemy>=2,<3",
]

[project.scripts]
recall-api = "recall_api:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "ruff>=0.16.9",
]
